run:
  timeout: 3m
  tests: false

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused

issues:
  max-same-issues: 50