name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.4.1
        with:
          version: v1.64.5

  unit-tests:
    name: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run unit tests
        run: go test -v ./... -short

  integration-tests:
    name: integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Start docker-compose
        run: docker compose -f docker-compose.yaml up -d --wait

      - name: Run integration tests
        run: go test -v -tags=integration ./...

      - name: Tear down docker-compose
        if: always()
        run: docker compose down
